Fix compatibility issue with wxWidgets 3.1.0
src/TextEditor/Lexer.cpp:119:28: error: too few arguments to function call, expected 2, have 1

wxStyledTextCtrl::StartStyling() has one parameter removed in wxWidgets 3.1.1
https://github.com/wxWidgets/wxWidgets/blob/v3.1.0/include/wx/stc/stc.h
https://github.com/wxWidgets/wxWidgets/blob/v3.1.1/include/wx/stc/stc.h
https://github.com/wxWidgets/wxWidgets/blob/v3.1.2/include/wx/stc/stc.h